In [1]:
# ==========================================================
# AI Diet Recommendation System
# Notebook 02 : Nutrition Dataset Exploration
# ==========================================================

print("🥗 Welcome to Notebook 02")
print("Nutrition Dataset Exploration")

🥗 Welcome to Notebook 02
Nutrition Dataset Exploration

In [2]:
# ==========================================================
# Import Libraries
# ==========================================================

import os

import pandas as pd

import numpy as np

In [3]:
# ==========================================================
# Project Folder
# ==========================================================

PROJECT_PATH = os.path.abspath("..")

print(PROJECT_PATH)

C:\Users\Pranai Teja Sabbe\Desktop\AI_Diet_Project

In [4]:
# ==========================================================
# Nutrition Dataset Path
# ==========================================================

NUTRITION_PATH = os.path.join(
    PROJECT_PATH,
    "datasets",
    "nutrition",
    "nutrition_data"
)

print(NUTRITION_PATH)

C:\Users\Pranai Teja Sabbe\Desktop\AI_Diet_Project\datasets\nutrition\nutrition_data

In [5]:
# ==========================================================
# Verify Nutrition Folder
# ==========================================================

print(os.path.exists(NUTRITION_PATH))

True

In [6]:
# ==========================================================
# Show Dataset Files
# ==========================================================

files = os.listdir(NUTRITION_PATH)

print("Files in Nutrition Dataset:\n")

for file in files:
    print(file)

Files in Nutrition Dataset:

acquisition_samples.csv
agricultural_samples.csv
Download API Field Descriptions.xlsx
food.csv
food_attribute.csv
food_attribute_type.csv
food_calorie_conversion_factor.csv
food_category.csv
food_component.csv
food_nutrient.csv
food_nutrient_conversion_factor.csv
food_portion.csv
food_protein_conversion_factor.csv
food_update_log_entry.csv
foundation_food.csv
input_food.csv
lab_method.csv
lab_method_code.csv
lab_method_nutrient.csv
market_acquisition.csv
measure_unit.csv
nutrient.csv
sample_food.csv
sub_sample_food.csv
sub_sample_result.csv

In [7]:
# ==========================================================
# Read food.csv
# ==========================================================

food_df = pd.read_csv(
    os.path.join(NUTRITION_PATH, "food.csv")
)

print("Dataset Loaded Successfully!")

food_df.head()

Dataset Loaded Successfully!

,fdc_id,data_type,description,food_category_id,publication_date
0,319874,sample_food,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
1,319875,market_acquisition,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
2,319876,market_acquisition,"HUMMUS, SABRA CLASSIC",16.0,2019-04-01
3,319877,sub_sample_food,Hummus,16.0,2019-04-01
4,319878,sub_sample_food,Hummus,16.0,2019-04-01

In [8]:
food_df.shape

(87990, 5)

In [9]:
food_df.columns

Index(['fdc_id', 'data_type', 'description', 'food_category_id',
       'publication_date'],
      dtype='object')

In [10]:
# ==========================================================
# Read nutrient.csv
# ==========================================================

nutrient_df = pd.read_csv(
    os.path.join(NUTRITION_PATH, "nutrient.csv")
)

print("Nutrient Dataset Loaded Successfully!")

nutrient_df.head()

Nutrient Dataset Loaded Successfully!

     id                               name unit_name  nutrient_nbr   rank
0  2047   Energy (Atwater General Factors)      KCAL         957.0  280.0
1  2048  Energy (Atwater Specific Factors)      KCAL         958.0  290.0
2  1001                             Solids         G         201.0  200.0
3  1002                           Nitrogen         G         202.0  500.0
4  1003                            Protein         G         203.0  600.0

In [11]:
nutrient_df.shape

(477, 5)

In [12]:
nutrient_df.columns

Index(['id', 'name', 'unit_name', 'nutrient_nbr', 'rank'], dtype='object')

In [13]:
# ==========================================================
# Read food_nutrient.csv
# ==========================================================

food_nutrient_df = pd.read_csv(
    os.path.join(NUTRITION_PATH, "food_nutrient.csv")
)

print("Food Nutrient Dataset Loaded Successfully!")

food_nutrient_df.head()

Food Nutrient Dataset Loaded Successfully!

C:\Users\Pranai Teja Sabbe\AppData\Local\Temp\ipykernel_36848\1214009540.py:5: DtypeWarning: Columns (9) have mixed types. Specify dtype option on import or set low_memory=False.
  food_nutrient_df = pd.read_csv(

,id,fdc_id,nutrient_id,amount,data_points,derivation_id,min,max,median,footnote,min_year_acquired
0,2201847,319877,1051,56.30,1.0,1.0,NaN,NaN,NaN,NaN,NaN
1,2201845,319877,1002,1.28,1.0,1.0,NaN,NaN,NaN,NaN,NaN
2,2201846,319877,1004,19.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN
3,2201844,319877,1007,1.98,1.0,1.0,NaN,NaN,NaN,NaN,NaN
4,2201852,319878,1091,188.00,1.0,1.0,NaN,NaN,NaN,NaN,NaN

In [14]:
food_nutrient_df.shape

(170469, 11)

In [15]:
food_nutrient_df.columns

Index(['id', 'fdc_id', 'nutrient_id', 'amount', 'data_points', 'derivation_id',
       'min', 'max', 'median', 'footnote', 'min_year_acquired'],
      dtype='object')

In [16]:
# ==========================================================
# Important Nutrients
# ==========================================================

important_nutrients = [
    "Protein",
    "Total lipid (fat)",
    "Carbohydrate, by difference",
    "Energy"
]

filtered_nutrients = nutrient_df[
    nutrient_df["name"].isin(important_nutrients)
]

filtered_nutrients

      id                         name unit_name  nutrient_nbr    rank
4   1003                      Protein         G         203.0   600.0
5   1004            Total lipid (fat)         G         204.0   800.0
6   1005  Carbohydrate, by difference         G         205.0  1110.0
9   1008                       Energy      KCAL         208.0   300.0
63  1062                       Energy        kJ         268.0   400.0

In [17]:
# ==========================================================
# Search for Banana
# ==========================================================

banana = food_df[
    food_df["description"].str.contains(
        "banana",
        case=False,
        na=False
    )
]

print("Total Banana Records Found:", len(banana))

banana.head(10)

Total Banana Records Found: 880

,fdc_id,data_type,description,food_category_id,publication_date
18899,790647,sample_food,"BANANAS, OVERRIPE",9.0,2020-04-01
18900,790648,market_acquisition,"BANANAS, OVERRIPE",9.0,2020-04-01
18901,790649,sub_sample_food,"BANANAS, OVERRIPE",9.0,2020-04-01
18902,790650,sub_sample_food,"BANANAS, OVERRIPE",9.0,2020-04-01
18903,790651,sub_sample_food,"BANANAS, OVERRIPE",9.0,2020-04-01
18904,790652,sub_sample_food,"BANANAS, OVERRIPE",9.0,2020-04-01
18905,790653,sub_sample_food,"BANANAS, OVERRIPE",9.0,2020-04-01
18906,790654,sub_sample_food,"BANANAS, OVERRIPE",9.0,2020-04-01
18907,790655,sub_sample_food,"BANANAS, OVERRIPE",9.0,2020-04-01
18908,790656,sub_sample_food,"BANANAS, OVERRIPE",9.0,2020-04-01